// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwo_j8btq-0jIf6z5n_eDzcZEN0YAn10',
    appId: '1:448479555877:web:6030dfdd2c7c2933c9eacc',
    messagingSenderId: '448479555877',
    projectId: 'kickscorner-905b1',
    authDomain: 'kickscorner-905b1.firebaseapp.com',
    storageBucket: 'kickscorner-905b1.appspot.com',
    measurementId: 'G-9VB1WG8BXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ08LKeyPyUojqrgwEJpCogXMSCpgyNBs',
    appId: '1:448479555877:android:e994ba31490d13b6c9eacc',
    messagingSenderId: '448479555877',
    projectId: 'kickscorner-905b1',
    storageBucket: 'kickscorner-905b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJ-e2M2cW8uNaZ4uz2d-GZMlc3V4sPb4',
    appId: '1:448479555877:ios:21339bc97dfdb045c9eacc',
    messagingSenderId: '448479555877',
    projectId: 'kickscorner-905b1',
    storageBucket: 'kickscorner-905b1.appspot.com',
    iosBundleId: 'com.example.kickscornerAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJ-e2M2cW8uNaZ4uz2d-GZMlc3V4sPb4',
    appId: '1:448479555877:ios:62c3cdbc826cfc22c9eacc',
    messagingSenderId: '448479555877',
    projectId: 'kickscorner-905b1',
    storageBucket: 'kickscorner-905b1.appspot.com',
    iosBundleId: 'com.example.kickscornerAdmin.RunnerTests',
  );
}
